### ISSUE TITLE
2x slowdown after switching from `markdown-to-react-components`

### ISSUE THREAD

**Issue by Pavek** [cerebral/marksy#5]
I tried to switch to `marksy` as recommend in now-deprecated `markdown-to-react-components` repo. Unfortunately I had to switch back after I saw that my build is about 2 times slower now (from ~30s to ~60s) which is big deal for us.

In a nutshell, my setup is a static website built with [Next.js][1] and I have about 150 `.md` files compiled during build.

[1]: https://github.com/zeit/next.js/

**Comment by christianalfoni** [comment]
@Pavek Hi there! Thanks for reporting.

So what you mean is compiling the markdown to React is slower? Cause `marksy` also has some extra dependencies, like `babel-standalone` which would increase the install time deploying code.

If it is the actual compiling of the MD files, could I ask if you have any HTML defined in them? If so there is a change now where that is also converted to actual React code.

If it is compile time and you are not defining any HTML in the MD files I need to investigate. Could you give an example as well? The API has changed, so wondering if you create a new instance of marksy everytime or use the same compile function?

**Comment by Pavek** [comment]
@christianalfoni ,

I saw `babel-standalone` dependency (and, btw, wondered how much it will add to the resulting bundle size, any ideas how much?). But no, this is not about `npm install` time - it is about actual compiling.

I have very little HTML in `.md` files. I found only 3 files with small HTML pieces similar to this:
```
<address>
Name <br/>
Title <br/>
<a href="mailto:email@examle.com">email@examle.com</a> <br/>
+1-111-1111-111 x110
</address>
```

Yes, I spotted the API changes and essentially I changed my code from this:
```
import MTRC from 'markdown-to-react-components';
MTRC.configure({ h4: H4, a: A }); // where A = ({ children: c }) => <a className="xx">{ c }</a>

export const MyComponent = ({ body }) => <div>{ MTRC(body).tree }</div>
```

To this:
```
import marksy from 'marksy';
const compile = marksy({ h4: H4, a: A });

export const MyComponent = ({ body }) => <div>{ compile(body).tree }</div>
```

And I have several components like this. So, yes it seems I'm creating new marksy instance at least once per component.

**Comment by christianalfoni** [comment]
@Pavek Sorry for my late reply and thanks so much taking time to write up the answer here, great stuff :)

1. I think the issue here is how HTML now is forced through babel-standalone logic

2. Do you need to create new marksy instance? I would suggest creating it once, unless you indeed need to have different definitions of elements in each instance

I will make an update to the library where babel-standalone is opt-in. Meaning by default you do not get the components and it will just return normal HTML, like in `markdown-to-react` components. Then you can opt-in to converting html/component with babel-standalone where:

1. Bundle size is only increased if you have opt in to this
2. By default you have to use the marksy language, like:

```js
/*
  ```marksy
    <SomeCustomComponent />
  ```
*/
```
3. You can opt-in to make it run on normal HTML as well

I will hack on this tomorrow and make a breaking publish with this new functionality, let me know if you have any concerns/suggestions related to this :-)

**Comment by christianalfoni** [comment]
@Pavek Hi man :-) Just released 1.0 where the components version is split into `marksy/components`... meaning you should just be able to update and get a boost in footprint and compilation time, as you `marksy` import now does not include that babel transpiling.

Please let me know how it works out for you :-)

**Comment by christianalfoni** [comment]
Hi again, just letting you know 3.0.0 is released... just wondering if it helped splitting it up?

**Comment by christianalfoni** [comment]
Closing this as it is old... hope it worked out for ya :)
